# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f3c5fae6121bc9a2e91dbda035fcda2fd418641542e732b70562520fa0e4b43d70f7a67e22fb3251eb9cdd873ec98a0e01c937a64dc19ad54f9f4ce2977ab46

test:
  secret_key_base: 0beba059d41545dfb4f1c95a8c981846ee6be8991cb99c2137414ffcc769a4eec9b615bd1d5b91769e5fc110953bceeb5905b8c652f8082957d5b5fa9f1aed9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
